### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by Ryuk4** [Harry-L-01/bonsaiWaterer#1]
Hello,

Just read your project on raspberrypi.org and I realised I've been working on a very similar project with real time updated charts. If you want to take a look here is the link to my project!
https://github.com/Ryuk4/Moduwat
It's good to see common interests!

**Comment by Harry-Lees** [comment]
your project looks really cool! I've just updated mine to use Flask as I was using the weird apache code injection before and flask seemed like a much better way of doing it!
